#!/bin/bash

# include common functions
source $(dirname "$0")/svn2git-include.sh

function help {
	echo
	echo "$(basename $0) [options] <svnRepo> <authorsFile> 2>&1 | tee ../ucsschool2svn.log"
	echo
	echo "<svnRepo>        Path to the Univention SVN dev repository"
	echo "<authorsFile>    Path to the SVN authors file in order to properly map usernames"
	echo "                 to real author names."
	echo  
	echo "Options:"
	echo "  -h, --help     Show this help only" 
	echo 
	echo "Checkout the UCS@school SVN repository via git-svn including rebasing branches"
	echo "for a continuous commit history."
	echo
}

function write_git_config {
	# only add the git-svn configuration in case it has not already been specified
	if ! grep -q svn-remote .git/config
	then
		cat >> .git/config <<EOF
[svn]
    authorsfile = $AUTHORS_FILE
    rmdir = true
[svn-remote "svn"]
	preserve-empty-dirs = true
	placeholder-filename = .git_keep_empty_dir
    url = $SVN
    fetch = trunk/component/ucsschool:refs/remotes/svn/trunk
    fetch = branches/ucs-2.2/component/ucsschool:refs/remotes/svn/ucsschool-2.2
    fetch = branches/ucs-2.3/component/ucsschool:refs/remotes/svn/ucsschool-2.3
    fetch = branches/ucs-2.4/ucs-school:refs/remotes/svn/ucsschool-2.4
    fetch = branches/ucs-3.0/ucs-school:refs/remotes/svn/ucsschool-3.0
    fetch = branches/ucs-3.1/ucs-school:refs/remotes/svn/ucsschool-3.1
    fetch = branches/ucs-3.1/ucs-school-r2:refs/remotes/svn/ucsschool-3.1r2
    fetch = branches/ucs-3.2/ucs-school-3.2:refs/remotes/svn/ucsschool-3.2
    fetch = branches/ucs-3.2/ucs-school-3.2r2:refs/remotes/svn/ucsschool-3.2r2
	fetch = branches/ucs-3.3/ucs-school-3.2r2:refs/remotes/svn/ucsschool-3.2r2b
    fetch = branches/ucs-4.0/ucs-school-4.0:refs/remotes/svn/ucsschool-4.0
    fetch = branches/ucs-4.0/ucs-school-4.0r2:refs/remotes/svn/ucsschool-4.0r2
    fetch = branches/ucs-4.1/ucs-school-4.1:refs/remotes/svn/ucsschool-4.1
    fetch = branches/ucs-4.1/ucs-school-4.1r2:refs/remotes/svn/ucsschool-4.1r2
    fetch = branches/ucs-4.2/ucs-school-4.2:refs/remotes/svn/ucsschool-4.2
EOF
	git config core.filemode false
	fi
}



SVN="$1"
AUTHORS_FILE="$2"

if [ "$1" = "-h" -o "$1" = "--help" -o "$#" != 2 ]
then
	help
	exit 0
fi

date

# basic sanity checks
check_git_repo
check_authors_file

# initial checkout of UCS repository via git-svn
write_git_config
git_svn_fetch
git gc
create_local_branches ucsschool master trunk

# rebase subtrees to obtain linear history
rebase ucsschool-2.2 trunk 10132
rebase ucsschool-3.0 ucsschool-2.4 30163
rebase ucsschool-3.2r2b ucsschool-3.2r2 69183
rebase ucsschool-4.0 ucsschool-3.2r2 54995

rewrite_commits_with_author_info
rename_branches 's/^ucsschool-//'

date
