#!/bin/bash

# include common functions
source $(dirname "$0")/svn2git-include.sh

function write_git_config {
	# only add the git-svn configuration in case it has not already been specified
	if ! grep -q svn-remote .git/config
	then
		cat >> .git/config <<EOF
[svn]
    authorsfile = $AUTHORS_FILE
    rmdir = true
[svn-remote "svn"]
	preserve-empty-dirs = true
	placeholder-filename = .git_keep_empty_dir
    url = $SVN
    fetch = trunk/component/ucsschool:refs/remotes/svn/trunk
    fetch = branches/ucs-2.2/component/ucsschool:refs/remotes/svn/ucsschool-2.2
    fetch = branches/ucs-2.3/component/ucsschool:refs/remotes/svn/ucsschool-2.3
    fetch = branches/ucs-2.4/ucs-school:refs/remotes/svn/ucsschool-2.4
    fetch = branches/ucs-3.0/ucs-school:refs/remotes/svn/ucsschool-3.0
    fetch = branches/ucs-3.1/ucs-school:refs/remotes/svn/ucsschool-3.1
    fetch = branches/ucs-3.1/ucs-school-r2:refs/remotes/svn/ucsschool-3.1r2
    fetch = branches/ucs-3.2/ucs-school-3.2:refs/remotes/svn/ucsschool-3.2
    fetch = branches/ucs-3.2/ucs-school-3.2r2:refs/remotes/svn/ucsschool-3.2r2
	fetch = branches/ucs-3.3/ucs-school-3.2r2:refs/remotes/svn/ucsschool-3.2r2b
    fetch = branches/ucs-4.0/ucs-school-4.0:refs/remotes/svn/ucsschool-4.0
    fetch = branches/ucs-4.0/ucs-school-4.0r2:refs/remotes/svn/ucsschool-4.0r2
    fetch = branches/ucs-4.1/ucs-school-4.1:refs/remotes/svn/ucsschool-4.1
    fetch = branches/ucs-4.1/ucs-school-4.1r2:refs/remotes/svn/ucsschool-4.1r2
    fetch = branches/ucs-4.2/ucs-school-4.2:refs/remotes/svn/ucsschool-4.2
EOF
	git config core.filemode false
	fi
}


SVN="$1"
AUTHORS_FILE="$2"

# basic sanity checks
check_args "$@"
check_git_repo
check_authors_file
date

# initial checkout of UCS repository via git-svn
write_git_config
git_svn_fetch
git gc
create_local_branches ucsschool master trunk
create_local_branches refs/remotes/svn/ 's|refs/remotes/svn/\(ucsschool-\)\?||' '/@[0-9]\+$/d' 

# rebase subtrees to obtain linear history
rebase 2.2 trunk 10132
rebase 3.0 2.4 30163
rebase 3.2r2b 3.2r2 69183
rebase 4.0 3.2r2 54995

rewrite_commits_with_author_info

date
