#!/bin/bash

# include common functions
source $(dirname "$0")/svn2git-include.sh

function write_git_config {
	# only add the git-svn configuration in case it has not already been specified
	if ! grep -q svn-remote .git/config
	then
		cat >> .git/config <<EOF
[svn]
    authorsfile = $AUTHORS_FILE
    rmdir = true
[svn-remote "svn"]
	preserve-empty-dirs = true
	placeholder-filename = .git_keep_empty_dir
    url = $SVN
	fetch = branches/ucs-4.2/ucc-3.0-integration:refs/remotes/svn/3.0/ucs-4.2
	fetch = branches/ucs-4.1/ucc-3.0-integration:refs/remotes/svn/3.0/ucs-4.1
	fetch = branches/ucs-4.1/ucc-2.1-integration:refs/remotes/svn/2.1/ucs-4.1
	fetch = branches/ucs-4.0/ucc-2.1-integration:refs/remotes/svn/2.1/ucs-4.0
	fetch = branches/ucs-4.0/ucc-integration:refs/remotes/svn/2.0/ucs-4.0
	fetch = branches/ucs-3.2/ucc-integration:refs/remotes/svn/1.0/ucs-3.2
	fetch = branches/ucs-3.1/ucc-integration:refs/remotes/svn/1.0/ucs-3.1
	fetch = branches/ucs-3.0/ucc-integration:refs/remotes/svn/1.0/ucs-3.0
EOF
	git config core.filemode false
	fi
}


SVN="$1"
AUTHORS_FILE="$2"

# basic sanity checks
check_args "$@"
check_git_repo
check_authors_file
date

# checkout of repository via git-svn
write_git_config
git_svn_fetch
git gc
create_local_branches refs/remotes/svn/ 's|refs/remotes/svn/||'

# rebase 3.2 onto 3.1 development
rebase 1.0/ucs-3.2 1.0/ucs-3.1 48435

# clean up
rewrite_commits_with_author_info

date
