#!/bin/bash

# include common functions
source $(dirname "$0")/svn2git-include.sh

function help {
	echo
	echo "$(basename $0) [options] <svnRepo> <authorsFile> 2>&1 | tee ../ucs2svn.log"
	echo
	echo "<svnRepo>        Path to the Univention SVN dev repository"
	echo "<authorsFile>    Path to the SVN authors file in order to properly map usernames"
	echo "                 to real author names."
	echo  
	echo "Options:"
	echo "  -h, --help     Show this help only" 
	echo 
	echo "Checkout the UCS SVN repository via git-svn including rebasing branches"
	echo "for a continuous commit history."
	echo
}

function write_git_config {
	# only add the git-svn configuration in case it has not already been specified
	if ! grep -q svn-remote .git/config
	then
		cat >> .git/config <<EOF
    filemode = false
[svn]
    authorsfile = $AUTHORS_FILE
    rmdir = true
[svn-remote "svn"]
	preserve-empty-dirs = true
	placeholder-filename = .git_keep_empty_dir
    url = $SVN
    fetch = trunk/ucs:refs/remotes/svn/trunk
    branches = branches/{ucs-2.0,ucs-2.1,ucs-2.2,ucs-2.3,ucs-2.4,ucs-3.0,ucs-3.1}/ucs:refs/remotes/svn/*
    branches = branches/ucs-3.1/{ucs-3.1-1,ucs-3.1-2}:refs/remotes/svn/*
    branches = branches/ucs-3.2/{ucs-3.2-0,ucs-3.2-1,ucs-3.2-2,ucs-3.2-3,ucs-3.2-4,ucs-3.2-5,ucs-3.2-6,ucs-3.2-7,ucs-3.2-8}:refs/remotes/svn/*
    branches = branches/ucs-3.3/{ucs-3.3-0,ucs-3.3-1}:refs/remotes/svn/*
    branches = branches/ucs-4.0/{ucs-4.0-0,ucs-4.0-1,ucs-4.0-2,ucs-4.0-3,ucs-4.0-4,ucs-4.0-5}:refs/remotes/svn/*
    branches = branches/ucs-4.1/{ucs-4.1-0,ucs-4.1-1,ucs-4.1-2,ucs-4.1-3,ucs-4.1-4}:refs/remotes/svn/*
    branches = branches/ucs-4.2/{ucs-4.2-0,ucs-4.2-1}:refs/remotes/svn/*
EOF
	fi
#	git config core.filemode false
}

function fetch_tags {
	svn ls -v "$SVN/tags" | sed -n '/ucsschool\|hotfix\|sec\|ucs2\.1-2/d; s/\s*\([0-9]\+\).*\(release-ucs.*\)\//\1 \2/p' | (
		while read irev itag
		do
			local patch_level_version=$(echo "$itag" | sed 's/release-ucs-\([0-9]\.[0-9]-[0-9]\).*/\1/')
			local minor_version=${patch_level_version%-*}
			icommit=''
			for ibranch in $patch_level_version $minor_version
			do
				icommit=$(get_preceding_rev "$ibranch" "$irev" 2> /dev/null)
				if [ -n "$icommit" ]
				then
					echo "Tagging: $itag -> $icommit"
					git tag "$itag" "$icommit"
					break
				fi
			done
			if [ -z "$icommit" ]
			then
				echo "Could not find the corresponding commit for $itag"
			fi
		done
	)
}

SVN="$1"
AUTHORS_FILE="$2"

if [ "$1" = "-h" -o "$1" = "--help" -o "$#" != 2 ]
then
	help
	exit 0
fi

date

# basic sanity checks
check_git_repo
check_authors_file

# initial checkout of UCS repository via git-svn
write_git_config
git_svn_fetch
git gc
create_local_branches refs/remotes/svn/ 's|refs/remotes/svn/\(ucs-\)\?||'

# Note that some packages have been moved from internal (e.g., ucslint) into 3.0
# while other packages have been moved from components (e.g., nagios). This
# history will not be kept in git.
rebase ucs-3.0 ucs-2.4 22331 
rebase ucs-3.2-0 ucs-3.1-2 41107
rebase ucs-3.2-2 ucs-3.2-1 49765
rebase ucs-4.0-0 ucs-3.2-2 51102

rewrite_commits_with_author_info
rename_branches 's/^ucs-//'

fetch_tags

date
