#!/bin/bash

# include common functions
source $(dirname "$0")/svn2git-include.sh

function write_git_config {
	# only add the git-svn configuration in case it has not already been specified
	if ! grep -q svn-remote .git/config
	then
		cat >> .git/config <<EOF
[svn]
    authorsfile = $AUTHORS_FILE
    rmdir = true
[svn-remote "svn"]
	preserve-empty-dirs = true
	placeholder-filename = .git_keep_empty_dir
    url = $SVN
	fetch = branches/ucs-4.1/ucc-3.0:refs/remotes/svn/3.0
	fetch = branches/ucs-4.0/ucc-2.1:refs/remotes/svn/2.1
	fetch = branches/ucs-3.2/ucc:refs/remotes/svn/2.0
	fetch = branches/ucs-3.1/ucc:refs/remotes/svn/1.0
	fetch = branches/ucs-3.0/ucc:refs/remotes/svn/1.0-alpha
EOF
	git config core.filemode false
	fi
}


SVN="$1"
AUTHORS_FILE="$2"

# basic sanity checks
check_args
check_git_repo
check_authors_file
date

# checkout of repository via git-svn
write_git_config
git_svn_fetch
git gc
create_local_branches refs/remotes/svn/ 's|refs/remotes/svn/||'

# rebase 2.0 onto 1.0 version
rebase 2.0 1.0 48433

# clean up
rewrite_commits_with_author_info

date
