#!/bin/bash

# include common functions
source $(dirname "$0")/svn2git-include.sh

function write_git_config {
	# only add the git-svn configuration in case it has not already been specified
	if ! grep -q svn-remote .git/config
	then
		cat >> .git/config <<EOF
[svn]
    authorsfile = $AUTHORS_FILE
    rmdir = true
[svn-remote "svn"]
    url = $SVN
    fetch = trunk/ucs:refs/remotes/svn/trunk
    branches = branches/{ucs-2.0,ucs-2.1,ucs-2.2,ucs-2.3,ucs-2.4,ucs-3.0,ucs-3.1}/ucs:refs/remotes/svn/*
    branches = branches/ucs-3.1/{ucs-3.1-1,ucs-3.1-2}:refs/remotes/svn/*
    branches = branches/ucs-3.2/{ucs-3.2-0,ucs-3.2-1,ucs-3.2-2,ucs-3.2-3,ucs-3.2-4,ucs-3.2-5,ucs-3.2-6,ucs-3.2-7,ucs-3.2-8}:refs/remotes/svn/*
    branches = branches/ucs-3.3/{ucs-3.3-0,ucs-3.3-1}:refs/remotes/svn/*
    branches = branches/ucs-4.0/{ucs-4.0-0,ucs-4.0-1,ucs-4.0-2,ucs-4.0-3,ucs-4.0-4,ucs-4.0-5}:refs/remotes/svn/*
    branches = branches/ucs-4.1/{ucs-4.1-0,ucs-4.1-1,ucs-4.1-2,ucs-4.1-3,ucs-4.1-4}:refs/remotes/svn/*
    branches = branches/ucs-4.2/{ucs-4.2-0,ucs-4.2-1,ucs-4.2-2}:refs/remotes/svn/*
EOF
	fi
	git config core.filemode true
}

function fetch_tags {
	svn ls -v "$SVN/tags" | sed -n '/ucsschool\|hotfix\|sec\|ucs2\.1-2/d; s/\s*\([0-9]\+\).*\(release-ucs.*\)\//\1 \2/p' | (
		while read irev itag
		do
			local patch_level_version=$(echo "$itag" | sed 's/release-ucs-\([0-9]\.[0-9]-[0-9]\).*/\1/')
			local minor_version=${patch_level_version%-*}
			icommit=''
			for ibranch in $patch_level_version $minor_version
			do
				icommit=$(get_preceding_rev "$ibranch" "$irev" 2> /dev/null)
				if [ -n "$icommit" ]
				then
					echo "Tagging: $itag -> $icommit"
					git tag "$itag" "$icommit"
					break
				fi
			done
			if [ -z "$icommit" ]
			then
				echo "Could not find the corresponding commit for $itag"
			fi
		done
	)
}

# fix some permissions that are not correctly respected during the migration
function fix_ucs30_permissions {
	chmod +x ./management/univention-directory-manager-module-example/scripts/ip-phone-tool
	chmod -x ./management/univention-directory-manager-modules/modules/univention/admin/__init__.py
	chmod -x ./management/univention-directory-manager-modules/modules/univention/admin/cron.py
	chmod -x ./management/univention-directory-manager-modules/modules/univention/admin/modules.py
	chmod +x ./base/univention-config-registry/python/univention-install-config-registry-info
	chmod +x ./base/univention-config-registry/scripts/univention-check-templates
	git commit --author='Univention GmbH <packages@univention.de>' -a -m "svn2git migration: explicitely fix some file permissions"
}


SVN="$1"
AUTHORS_FILE="$2"

# basic sanity checks
check_args "$@"
check_git_repo
check_authors_file
date

# initial checkout of UCS repository via git-svn
write_git_config
git_svn_fetch
git gc
create_local_branches refs/remotes/svn/ 's|refs/remotes/svn/\(ucs-\)\?||'

# Note that some packages have been moved from internal (e.g., ucslint) into 3.0
# while other packages have been moved from components (e.g., nagios). This
# history will not be kept in git.
rebase 3.0 2.4 22331 fix_ucs30_permissions
rebase 3.2-0 3.1-2 41107
rebase 3.2-2 3.2-1 49765
rebase 4.0-0 3.2-2 51102

rewrite_commits_with_author_info

fetch_tags

date
